### PR TITLE
Move privacy_mode_enabled to Music.App

### PR DESCRIPTION
**Pull request by danrabbit**
Appears to never be used by plugins

### CODE REVIEW

**Comment by jeremypw** [comment]
The plugins can and do save data to disk (but do not check the privacy setting). E.g the LastFM plugin saves cover art (Core.vala line 239 et seq) and the AudioPlayerLibrary updates playlists (AudioPlayerLibrary.vala line 399 et seq).  Not sure if these are privacy issues but before making this change should audit whether the any plugins *should* be using the privacy setting.

**Comment by jeremypw** [comment]
@danrabbit Are you satisfied that there are no privacy issues regarding the kind of data that plugins save?  If so I will approve this.

**Comment by danrabbit** [comment]
@jeremypw I've started working on a complete rewrite in another branch so I'm kind of indifferent to continuing to refactor here. I'll leave it to your discretion to merge or close

**Comment by jeremypw** [comment]
Closing in favour of planned new PR

**Pull request closed without merging**
