### PR TITLE
TrackRow: add animated playback indicator

### PR DESCRIPTION
**Pull request by danrabbit**
* Create TrackRow
* Add an animated playback indicator
* Set accent color to orange

### CODE REVIEW

**Comment by jeremypw** [comment]
@danrabbit When I build and install this I only get the simplified player, not the full app - is that intentional?  Looks cool though :smile:

MusicPlaybackIndicator

**Comment by jeremypw** [comment]
Also, there seems to be no mandatory review on this project.

**Comment by danrabbit** [comment]
@jeremypw yeah this branch is actually a total rewrite I've been working on in my spare time! I'm trying to get the basics down before adding any major features like a library or anything. It's very much a work in progress haha

**Comment by jeremypw** [comment]
@danrabbit Ah, OK.  Should it be set to "Draft" then?

**Comment by danrabbit** [comment]
@jeremypw sorry I meant the branch "main" is the rewrite as opposed to the current focused branch which is "master". This branch is a PR to "main", so it's not currently building in dailies or anything like that :)

**Comment by jeremypw** [comment]
Oh, sorry - I got confused between `main` and `master`.

**Pull request merged**
