### PR TITLE
Make the queue mechanism less confusing

### LINKED ISSUE #2: The queue mechanism is a bit confusing
The way the queue works is a bit confusing for several reasons.

1)  it is populated manually (right click enqueue). 
Yet when the user double clicks on a media, the media is played automatically but the queue is not updated: the media coming next to the double clicked media will play (but will not show in the queue)

2) how should play/next/previous buttons work?
Should they play the currently selected track or play the queue playlist

Also, the queue is not persisted: it is lost when the application exits.

The iTunes queue is nice insofar it always shows what will the next track be and let the user re order and remove tracks.

Note: the technical solution must scale for large libraries.

Launchpad Details: [#LP1382879](https://bugs.launchpad.net/bugs/1382879) PerfectCarl - 2014-10-18 23:31:33 +0000

### PR DESCRIPTION
**Pull request by Bat41**
Fix #2 #54 #42

Now, when you double-click on a song, it is played and other songs of
the current list are added to the queue.

Shuffling and repeating are now acting on the songs which are queued.

Also improved the style of some parts of the code, and changed many
Gee.HashMap<int, Media> to ArrayList<int, Media> (they were acting as
arrays, I don't know why they were maps).

I made many changes, so I hope I didn't broke anything. :grin:

### CODE REVIEW

**Comment by matzipan** [comment]
Hey, thanks for the pull request, but it seems like this should be broken up into 3 different pull requests one for each change: gitignore, cd imports and queue mechanism. This is because pull reuqests are merged through squash and merge and it wouldn't make sense to merge these 3 separate changes into a single commit. 

Thanks!

**Comment by Bat41** [comment]
Yes, I didn't noticed this. That's strange because the two first have been merged in previous pull requests…

**Comment by matzipan** [comment]
Then it means you need to pull from upstream master and merge.

**Comment by Bat41** [comment]
Well, I'm realizing I can't because one of these commits have not been merged (the .gitignore one).

**Comment by matzipan** [comment]
Submit the gitignore stuff as a separate pull request on its own and I will merge it straight away, and make sure the rest of the changes are reviewed and merged.

You might find it more easy to communicate if you join the elementary community slack: https://elementarycommunity.herokuapp.com/

**Pull request closed without merging**
