### PR TITLE
Enable playback buttons on startup if media is available

### LINKED ISSUE #570: Playback buttons are disabled on startup
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The playback buttons (previous, play/pause, forward) are disabled when starting Music even with available files in the library. Also after importing music for the first time.

### To Reproduce
1. Copy music files to the user Music folder.
2. Open Music app and let it detect/import the music.
3. Note that when step 2 is done, the playback buttons remain disabled.
4. Only way to start playing music is to double-click on a media entry in the list.
5. Close and reopen Music, same issue even though music files are available.

### Expected behavior

Music should be able to start with playback buttons enabled when media is available.

## Platform Information

- [x] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

### PR DESCRIPTION
**Pull request by vjr**
Fixes #570

### CODE REVIEW

**Comment by vjr** [comment]
Not sure why the Travis CI build is failing but in the details I noticed it still has `xenial` configured.

**Comment by vjr** [comment]
I am not seeing this behaviour but let me look into it some more.

**Comment by vjr** [comment]
> After starting Music, the playback buttons are enabled but pressing play does not play anything because no track is selected. Instead I get an error in the terminal:
> 
> ```
> ** (io.elementary.music:24216): CRITICAL **: 18:08:00.034: music_playback_manager_play_media: assertion 'm != NULL' failed
> ```
> 
> I think you need to select a track after start up for this to work (which may cause the buttons to become sensitive anyway - although I have not investigated the code).

Addressed.

**Comment by vjr** [comment]
I can't figure out how to switch this PR from "changes requested" (which is addressed now) to "review requested", SMH.

**Comment by jeremypw** [comment]
The only slight issue I have is that the app seems to start at a random track when the "last-media-playing" setting is the default value of "0".  However, I guess this will only occur very rarely (generally on first use of app) so may not be worth fixing, at least not necessarily in this PR.

**Comment by jeremypw** [comment]
You can get rid of "changes requested" by dismissing a stale review (if you have the rights) otherwise the reviewer has to do it.

**Comment by vjr** [comment]
Thanks for the review/approve. Yeah looks like I don't have rights to dismiss the "changes requested".

**Comment by vjr** [comment]
Travis CI is still failing with the following:

```
$ houston ci --type system-app --name-domain io.elementary.music --name-human Music
THIS COMMAND IS NOT FULLY COMPLETE
IT ONLY WORKS ON GITHUB WITH TRAVIS AT THIS TIME
Testing "/home/travis/build/elementary/music" project for "https://github.com/elementary/music"
/home/travis/.travis/functions: line 109:  6101 Segmentation fault      (core dumped) houston ci --type system-app --name-domain io.elementary.music --name-human Music
The command "houston ci --type system-app --name-domain io.elementary.music --name-human Music" exited with 139.
```
Do you know what this is about?

**Comment by vjr** [comment]
> The only slight issue I have is that the app seems to start at a random track when the "last-media-playing" setting is the default value of "0". However, I guess this will only occur very rarely (generally on first use of app) so may not be worth fixing, at least not necessarily in this PR.

There's something going on with the `reshuffle ()` function at https://github.com/elementary/music/blob/39291b13a9296f1607cb8be4c70cb163bdee1fd6/src/PlaybackManager.vala#L215 as if the `shuffle_mode` setting is not being read properly, but yes, I guess that can be looked at in another PR. (I'll try taking a stab at another PR).

**Comment by jeremypw** [comment]
I am just to about to push a PR that should fix the CI failure. It has been happening to a number of projects after a node_js update.  Need to specify a particular version, not the latest.

**Comment by vjr** [comment]
Is this OK to merge to master now? (checks have passed and i can't merge it)

**Pull request merged**
