### PR TITLE
Work around play icon spinner sometimes not spinning.

### PR DESCRIPTION
**Pull request by vjr**
Fixes in three places:

* When you first open the app then select multiple tracks from the Files app the first track play icon spinner was stuck.
* When selecting different tracks in the playlist/queue the spinner would sometimes get stuck.
* When clicking the play/pause button repeatedly sometimes the spinner would get stuck.

### CODE REVIEW

**Review by danirabbit — DISMISSED** [review]
I'm not a huge fan of adding timeouts with magic numbers, but can we at least add a comment that this is a workaround and a link to the upstream issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/4426

**Comment by vjr** [comment]
> I'm not a huge fan of adding timeouts with magic numbers, but can we at least add a comment that this is a workaround and a link to the upstream issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/4426

The 250 ms timeout could be an issue if there are tens of thousands of tracks (`TrackRow`s) each connecting to the `current-audio` property notification of the PlaybackManager?

**Comment by zeebok** [comment]
Looks like the upstream has a fix in? If so, this should be re-evaluated.

**Comment by danirabbit** [comment]
Yeah this was recently fixed upstream so I'm not sure it's worth carrying this workaround when a platform update will solve it automatically

**Comment by vjr** [comment]
Oh good to hear it's fixed upstream. Do we want to close this PR right away or wait until the fix actually lands in an update?

**Comment by danirabbit** [comment]
Yeah, I feel like we should probably just wait for a platform update with a newer Gtk release and not carry the workaround since it's a pretty minor bug

**Pull request closed without merging**
