### PR TITLE
Built-in MPRIS

### LINKED ISSUE #108: Built in MPRIS
MPRIS should be supported without any plugin.

### PR DESCRIPTION
**Pull request by Bat41**
Fixes #108 

Before testing, make sure to uninstall the old MPRIS plugin or to disable it by setting `org.pantheon.noise.settings.plugins-disabled` to `['mpris']`. If you don't, some types will be registered two times, and the app will just crash. I don't know if the plugin will be uninstalled when users will update.

### CODE REVIEW

**Comment by Nine-H** [comment]
build failed
`fatal error: libindicate/listener.h: No such file or directory`
I have `libindicate-dev` and `libindicate-gtk3-dev` installed, please advise.

**Comment by Thalexander** [comment]
dpkg shows that file as owned by libindicate-dev so it should work if you have it installed, maybe try a restart to see if it updates the path.
libindicate-dev: /usr/include/libindicate-0.7/libindicate/listener.h

**Comment by tintou** [comment]
It would probably better to rewrite the MPRIS support without libindicate and Dbusmenu-0.4, it seems like no one is using those libraries directly

**Comment by tintou** [comment]
Noise.MPRIS should probably just be a namespace containing two static functions, otherwise it looks very good

**Comment by tintou** [comment]
Looks great!

**Pull request merged**
