### PR TITLE
Fix data files so Music has an icon in AppCenter

### PR DESCRIPTION
**Pull request by lainsce**
Should merge #512 soon after this one.

Overall, this PR will fix most problems in the data folder.

- Fixed some lack of linking the data folder in `meson.build` files, and also the `gresource` file,
so that Music has an icon in AppCenter.
- Also removed the duplicate icons in the data folder as they were unused.
- Fix tabbing in the appdata.xml file as XML is tab-sensitive.

Despite the Travis CI :x: this is stable.

### CODE REVIEW

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your PR!
Do you think you can fix that for the other apps as well? https://github.com/elementary/music/issues/334#issuecomment-516761373

**Comment by lainsce** [comment]
I'll gradually do it.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for working on that! Is the procedure for the other mentioned apps similar to your fix for music?

**Comment by lainsce** [comment]
It should be.

**Comment by 4jNsY6fCVqZv** [comment]
But not for Firefox and GStreamer Multimedia Codecs as third party packages, right?

Hmm, that would be my first fix ever. At the moment, for example, the file structure of the projects also looks different. If you guide me, I can try to prepare PR's for Screenshot and Code.

When will your PR be merged?

**Comment by lainsce** [comment]
> But not for Firefox and GStreamer Multimedia Codecs as third party packages, right?

Yeah, those are outside my reach as an elementary developer.

> When will your PR be merged?

Whenever there is an approving review.

**Comment by davidmhewitt** [comment]
There are a number of seemingly unrelated changes here, this is very difficult to review. 

There's probably some good stuff in here in terms of tidying stuff up but it would be better if you separated this out into different pull requests. It's hard to review changes to translation files, deletion of icons, massive whitespace and markup changes in XML (which by the way isn't indentation sensitive), and inexplicably no longer installing the icons to the `hicolor/apps` folder anymore all in one PR?

Given that the issue with icons not appearing in AppCenter is caused by the `appstream-data-pantheon` package (see https://github.com/elementary/appstream-data/issues/13), and I've tested and proven a fix where the icons for Music appear in AppCenter without this being merged, I'd be tempted to close this so it can be broken down into individual cleanup PRs.

**Comment by danrabbit** [comment]
Yeah I agree with @davidmhewitt. This is (almost certainly) not the cause of those issues and it would be better to provide smaller, individual PRs for other cleanup

**Pull request closed without merging**
