### PR TITLE
Use signal to notify when to show error toast

### PR DESCRIPTION
**Pull request by ZenitsuDev**
Aims to help with https://github.com/elementary/music/pull/711

@vjr I tried it :)

### CODE REVIEW

**Comment by vjr** [comment]
Thanks for this!

What if I import large number of files and there are many invalid files? Will there be a flood of toasts?

I'll test your branch later today , thanks again!

**Comment by ZenitsuDev** [comment]
@vjr unfortunately yes at least in this way, they would appear one after another. maybe we can stockpile invalid filenames in an array and show them in one go.

**Comment by vjr** [comment]
@ZenitsuDev  I made a change to only show one toast with the count of invalid files. If this part looks OK to you I can merge to my branch and we can continue working on that single branch for easier review from the devs.

**Comment by ZenitsuDev** [comment]
@vjr yeah sure! I think just showing the numbers is good

**Pull request merged**
