### PR TITLE
Resolving #264 by changing how to get the next/previous media in a playlist

### LINKED ISSUE #264: Starting a track and clicking the previous track button causes playback to stop.
```
[DEBUG 22:26:18.738306] ViewWrapper.vala:447: SETTING MEDIA [NOISE_VIEW_WRAPPER_HINT_READ_ONLY_PLAYLIST]
[DEBUG 22:26:18.753624] LibraryWindow.vala:652: UPDATE SENSITIVITIES
[DEBUG 22:26:18.758911] LibraryWindow.vala:935: playback stopped
[DEBUG 22:26:18.759991] LibraryWindow.vala:652: UPDATE SENSITIVITIES
[DEBUG 22:26:18.760803] LibraryWindow.vala:935: playback stopped
[DEBUG 22:26:18.761350] LibraryWindow.vala:652: UPDATE SENSITIVITIES
```
I don't think the debug message from ViewWrapper.vala is very useful because it always returns NOISE_VIEW_WRAPPER_HINT_READ_ONLY_PLAYLIST

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/54403083-starting-a-track-and-clicking-the-previous-track-button-causes-playback-to-stop?utm_campaign=plugin&utm_content=tracker%2F60766398&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60766398&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ZavierHenry**
Fixes #264
So to resolve this, I had to discriminate between advancing through the playlist normally and advancing forward/backward by pressing the next/previous button

### CODE REVIEW

**Comment by jeremypw** [comment]
This seems a lot of code to fix, on the face, of it a small bug.  Could you explain what the difference between "play_next" and "simple_play_next" and why you need to distingish them?

**Comment by ZavierHenry** [comment]
Sure. Unlike "play_next", "simple_play_next" ignores playback options. At least with the players I tried, playback options are only considered when the song ends, not when the next/previous button is pressed, which needs to discriminate them.

#264 is happening because of this line
image

When you click the previous button after clicking a song to play, the player handles it as if it was the final song of the playlist. You get the same behavior if you click the next button through every song in the playlist until you get back to the first clicked song.

**Comment by ZavierHenry** [comment]
Thinking about it though, it could probably just be one function with a boolean for playback options instead of two separate functions

**Comment by jeremypw** [comment]
It sounds like an extra boolean parameter defaulting to true (`bool follow_playback_options = true`) would be a more efficient solution.

**Comment by ZavierHenry** [comment]
Ok the changes have been made

**Comment by ZavierHenry** [comment]
I don't think I quite understand what you're saying, or maybe I didn't explain what it meant to ignore playback options well enough. 

Edit: Looking at the original get_next function again I think I actually used the wrong terminology. When I said that pressing the next/previous buttons should ignore playback options, I meant it should ignore <em><strong>repeat</em></strong> options, whether it's repeating a song or repeating an album. 

The option to shuffle a playlist should remain unaffected and the next/previous button should play the next/previous song of the shuffled playlist.

**Comment by jeremypw** [comment]
This is my refactoring.  It does not save that many total lines as it is more spread out but I think it is a little clearer:

```
    public Media? get_next (bool play, bool consider_repeat = true) {
        Media? rv = null;
        _playing_queued_song = false;
        var main_settings = Settings.Main.get_default ();
        var repeat_mode = main_settings.repeat_mode;

        if (main_settings.shuffle_mode != Noise.Settings.Shuffle.OFF) { /* Shuffle on */
            debug ("Shuffled size: %d", _current_shuffled.size);
            if (_current_shuffled.is_empty) {
                if (_current.is_empty) {
                    queue_media (library.get_medias ()); // first initialize the current selection the reshuffle it
                }

                reshuffle ();
            }

            rv = get_next_media (_current_shuffled, ref _current_shuffled_index, consider_repeat, repeat_mode);

            if (rv == null && repeat_mode != Noise.Settings.Repeat.OFF) { /* If failed to get next media, start again */
                set_shuffle_mode (Noise.Settings.Shuffle.ALL);
                reshuffle ();
                _current_shuffled_index = 0;
                rv = _current_shuffled.get (0);
            }
        } else {
            rv = get_next_media (_current, ref _current_index, consider_repeat, repeat_mode);

            if (rv == null && repeat_mode != Noise.Settings.Repeat.OFF) {
                queue_media (library.get_medias ());
                _current_index = 0;
                rv = _current.get (0);
            }
        }

        if (rv == null) {
            if (play) {
warning ("stopping");
                stop_playback ();
            }

            return null;
        }

        _playing_queued_song = queue_playlist.medias.contains (rv);

        if (play) {
            play_media (rv);
        }

        return rv;
    }

    /*** @collection is either the current list or the shuffled list
         @index is a reference to the index into the collection of the current media
        Should cause play to stop of returns null
     ***/
    private Media? get_next_media (Gee.HashMap<int, Media> collection,
                                   ref int index,
                                   bool consider_repeat,
                                   Noise.Settings.Repeat repeat_mode) {

        if (current_media == null) {
            index = -1;
        } else if (consider_repeat) {
            Media? next_media = null;
            var next_index = index + 1;

            if (next_index >= 0 && next_index < collection.size) {
                next_media = collection.@get (index + 1);
            }

            switch (repeat_mode) {
                case Noise.Settings.Repeat.ALBUM:
                    if (next_media == null || next_media.album != current_media.album) {
                        while (--index >= 0 && collection.get (index).album == current_media.album) {}
                        break;
                    }

                    break;

                case Noise.Settings.Repeat.ARTIST:
                    if (next_media == null || next_media.artist != current_media.artist) {
                        while (--index >= 0 && collection.get (index).artist == current_media.artist) {}
                        break;
                    }

                    break;

                case Noise.Settings.Repeat.MEDIA:
                    index--;
                    break;

                case Noise.Settings.Repeat.ALL:
                    break;

                case Noise.Settings.Repeat.OFF:
                    if (next_media == null) {
                        return null;
                    }

                    break;

                default:
                    warning ("Unexpected repeat mode %s", repeat_mode.to_string ());
                    return null;
            }
        }

        /* The following also takes care of Repeat.ALL and ignore repeat options */
        index++;
        if (index == collection.size) {
            index = 0;
        }

        return collection.@get (index);
    }
```

Still needs some testing though.

**Comment by jeremypw** [comment]
@ZavierHenry Hi, is this PR still alive or has it been abandoned?

**Comment by jeremypw** [comment]
Closing as has unaddressed issues and no recent activity. Please feel free to reopen (as draft) if you wish to continue working on it. I think we need to define exactly what the expected behaviour is under each circumstance - the bug report does not make this clear.

**Pull request closed without merging**
